version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: pharmops-postgres
    restart: always
    environment:
      POSTGRES_DB: pharmops
      POSTGRES_USER: pharmops
      POSTGRES_PASSWORD: pharmops
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pharmops-net

  api-gateway:
    build: ./services/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - drug-catalog-service
    networks:
      - pharmops-net

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pharmops
      SPRING_DATASOURCE_USERNAME: pharmops
      SPRING_DATASOURCE_PASSWORD: pharmops
    depends_on:
      - postgres
    networks:
      - pharmops-net

  drug-catalog-service:
    build: ./services/drug-catalog-service
    container_name: drug-catalog-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pharmops
      SPRING_DATASOURCE_USERNAME: pharmops
      SPRING_DATASOURCE_PASSWORD: pharmops
    depends_on:
      - postgres
    networks:
      - pharmops-net

  notification-service:
    build: ./services/notification-service
    container_name: notification-service
    ports:
      - "3000:3000"
    networks:
      - pharmops-net

  pharma-ui:
    build: ./services/pharma-ui
    container_name: pharma-ui
    ports:
      - "80:80"
    depends_on:
      - api-gateway
    networks:
      - pharmops-net

volumes:
  postgres_data:

networks:
  pharmops-net:
    driver: bridge
